name: Deploy UI to cloud

on:
  push:
    branches:
      - main
      - hotfix/cors

defaults:
  run:
    working-directory: ./ui

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Replace environment file
        run: |
          cp src/environments/environments.main.js src/environments/environments.js

      - name: Install and Build
        run: |
          yarn install
          yarn build
          pwd
          ls .

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: ui/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}